package com.devflow.project.events;

public enum ProjectEventType {
    PROJECT_CREATED,
    PROJECT_UPDATED,
    PROJECT_ARCHIVED,
    PROJECT_RESTORED,
    PROJECT_DELETED,
    PROJECT_MEMBER_ADDED,
    PROJECT_MEMBER_REMOVED,
    PROJECT_MEMBER_ROLE_CHANGED,
    PROJECT_OWNERSHIP_TRANSFERRED,
    PROJECT_STATUS_CHANGED,
    PROJECT_HEALTH_CHANGED,
    PROJECT_SETTINGS_UPDATED,
    PROJECT_TAG_CREATED,
    PROJECT_TAG_UPDATED,
    PROJECT_TAG_DELETED,
    PROJECT_FAVORITED,
    PROJECT_UNFAVORITED
}
