/**
 * Static ISO-3166 country reference data shared by `CountrySelect` and
 * `PhoneInput`. No network/API calls — this is reference data, not business
 * data, so it's safe to ship as a static module in a form-primitives system.
 */
export interface Country {
  /** ISO 3166-1 alpha-2 code, e.g. "US". */
  code: string;
  name: string;
  /** E.164 calling code, e.g. "+1". */
  dialCode: string;
}

/**
 * Converts an ISO 3166-1 alpha-2 code into its flag emoji using Unicode
 * regional indicator symbols — no image/icon assets required.
 */
export function getFlagEmoji(iso2: string): string {
  return iso2
    .toUpperCase()
    .replace(/./g, (char) => String.fromCodePoint(127397 + char.charCodeAt(0)));
}

export const countries: Country[] = [
  { code: "US", name: "United States", dialCode: "+1" },
  { code: "CA", name: "Canada", dialCode: "+1" },
  { code: "GB", name: "United Kingdom", dialCode: "+44" },
  { code: "AU", name: "Australia", dialCode: "+61" },
  { code: "NZ", name: "New Zealand", dialCode: "+64" },
  { code: "IE", name: "Ireland", dialCode: "+353" },
  { code: "IN", name: "India", dialCode: "+91" },
  { code: "PK", name: "Pakistan", dialCode: "+92" },
  { code: "BD", name: "Bangladesh", dialCode: "+880" },
  { code: "LK", name: "Sri Lanka", dialCode: "+94" },
  { code: "NP", name: "Nepal", dialCode: "+977" },
  { code: "CN", name: "China", dialCode: "+86" },
  { code: "JP", name: "Japan", dialCode: "+81" },
  { code: "KR", name: "South Korea", dialCode: "+82" },
  { code: "KP", name: "North Korea", dialCode: "+850" },
  { code: "TW", name: "Taiwan", dialCode: "+886" },
  { code: "HK", name: "Hong Kong", dialCode: "+852" },
  { code: "MO", name: "Macau", dialCode: "+853" },
  { code: "MN", name: "Mongolia", dialCode: "+976" },
  { code: "SG", name: "Singapore", dialCode: "+65" },
  { code: "MY", name: "Malaysia", dialCode: "+60" },
  { code: "ID", name: "Indonesia", dialCode: "+62" },
  { code: "PH", name: "Philippines", dialCode: "+63" },
  { code: "TH", name: "Thailand", dialCode: "+66" },
  { code: "VN", name: "Vietnam", dialCode: "+84" },
  { code: "KH", name: "Cambodia", dialCode: "+855" },
  { code: "LA", name: "Laos", dialCode: "+856" },
  { code: "MM", name: "Myanmar", dialCode: "+95" },
  { code: "BN", name: "Brunei", dialCode: "+673" },
  { code: "TL", name: "Timor-Leste", dialCode: "+670" },
  { code: "DE", name: "Germany", dialCode: "+49" },
  { code: "FR", name: "France", dialCode: "+33" },
  { code: "ES", name: "Spain", dialCode: "+34" },
  { code: "PT", name: "Portugal", dialCode: "+351" },
  { code: "IT", name: "Italy", dialCode: "+39" },
  { code: "NL", name: "Netherlands", dialCode: "+31" },
  { code: "BE", name: "Belgium", dialCode: "+32" },
  { code: "LU", name: "Luxembourg", dialCode: "+352" },
  { code: "CH", name: "Switzerland", dialCode: "+41" },
  { code: "AT", name: "Austria", dialCode: "+43" },
  { code: "SE", name: "Sweden", dialCode: "+46" },
  { code: "NO", name: "Norway", dialCode: "+47" },
  { code: "DK", name: "Denmark", dialCode: "+45" },
  { code: "FI", name: "Finland", dialCode: "+358" },
  { code: "IS", name: "Iceland", dialCode: "+354" },
  { code: "PL", name: "Poland", dialCode: "+48" },
  { code: "CZ", name: "Czech Republic", dialCode: "+420" },
  { code: "SK", name: "Slovakia", dialCode: "+421" },
  { code: "HU", name: "Hungary", dialCode: "+36" },
  { code: "RO", name: "Romania", dialCode: "+40" },
  { code: "BG", name: "Bulgaria", dialCode: "+359" },
  { code: "GR", name: "Greece", dialCode: "+30" },
  { code: "CY", name: "Cyprus", dialCode: "+357" },
  { code: "MT", name: "Malta", dialCode: "+356" },
  { code: "HR", name: "Croatia", dialCode: "+385" },
  { code: "SI", name: "Slovenia", dialCode: "+386" },
  { code: "RS", name: "Serbia", dialCode: "+381" },
  { code: "BA", name: "Bosnia and Herzegovina", dialCode: "+387" },
  { code: "ME", name: "Montenegro", dialCode: "+382" },
  { code: "MK", name: "North Macedonia", dialCode: "+389" },
  { code: "AL", name: "Albania", dialCode: "+355" },
  { code: "XK", name: "Kosovo", dialCode: "+383" },
  { code: "EE", name: "Estonia", dialCode: "+372" },
  { code: "LV", name: "Latvia", dialCode: "+371" },
  { code: "LT", name: "Lithuania", dialCode: "+370" },
  { code: "UA", name: "Ukraine", dialCode: "+380" },
  { code: "BY", name: "Belarus", dialCode: "+375" },
  { code: "MD", name: "Moldova", dialCode: "+373" },
  { code: "RU", name: "Russia", dialCode: "+7" },
  { code: "GE", name: "Georgia", dialCode: "+995" },
  { code: "AM", name: "Armenia", dialCode: "+374" },
  { code: "AZ", name: "Azerbaijan", dialCode: "+994" },
  { code: "KZ", name: "Kazakhstan", dialCode: "+7" },
  { code: "UZ", name: "Uzbekistan", dialCode: "+998" },
  { code: "TM", name: "Turkmenistan", dialCode: "+993" },
  { code: "TJ", name: "Tajikistan", dialCode: "+992" },
  { code: "KG", name: "Kyrgyzstan", dialCode: "+996" },
  { code: "TR", name: "Turkey", dialCode: "+90" },
  { code: "IL", name: "Israel", dialCode: "+972" },
  { code: "PS", name: "Palestine", dialCode: "+970" },
  { code: "JO", name: "Jordan", dialCode: "+962" },
  { code: "LB", name: "Lebanon", dialCode: "+961" },
  { code: "SY", name: "Syria", dialCode: "+963" },
  { code: "IQ", name: "Iraq", dialCode: "+964" },
  { code: "IR", name: "Iran", dialCode: "+98" },
  { code: "SA", name: "Saudi Arabia", dialCode: "+966" },
  { code: "AE", name: "United Arab Emirates", dialCode: "+971" },
  { code: "QA", name: "Qatar", dialCode: "+974" },
  { code: "BH", name: "Bahrain", dialCode: "+973" },
  { code: "KW", name: "Kuwait", dialCode: "+965" },
  { code: "OM", name: "Oman", dialCode: "+968" },
  { code: "YE", name: "Yemen", dialCode: "+967" },
  { code: "AF", name: "Afghanistan", dialCode: "+93" },
  { code: "EG", name: "Egypt", dialCode: "+20" },
  { code: "LY", name: "Libya", dialCode: "+218" },
  { code: "TN", name: "Tunisia", dialCode: "+216" },
  { code: "DZ", name: "Algeria", dialCode: "+213" },
  { code: "MA", name: "Morocco", dialCode: "+212" },
  { code: "SD", name: "Sudan", dialCode: "+249" },
  { code: "SS", name: "South Sudan", dialCode: "+211" },
  { code: "ET", name: "Ethiopia", dialCode: "+251" },
  { code: "ER", name: "Eritrea", dialCode: "+291" },
  { code: "DJ", name: "Djibouti", dialCode: "+253" },
  { code: "SO", name: "Somalia", dialCode: "+252" },
  { code: "KE", name: "Kenya", dialCode: "+254" },
  { code: "UG", name: "Uganda", dialCode: "+256" },
  { code: "TZ", name: "Tanzania", dialCode: "+255" },
  { code: "RW", name: "Rwanda", dialCode: "+250" },
  { code: "BI", name: "Burundi", dialCode: "+257" },
  { code: "NG", name: "Nigeria", dialCode: "+234" },
  { code: "GH", name: "Ghana", dialCode: "+233" },
  { code: "CI", name: "Ivory Coast", dialCode: "+225" },
  { code: "SN", name: "Senegal", dialCode: "+221" },
  { code: "ML", name: "Mali", dialCode: "+223" },
  { code: "BF", name: "Burkina Faso", dialCode: "+226" },
  { code: "NE", name: "Niger", dialCode: "+227" },
  { code: "TD", name: "Chad", dialCode: "+235" },
  { code: "CM", name: "Cameroon", dialCode: "+237" },
  { code: "CF", name: "Central African Republic", dialCode: "+236" },
  { code: "GA", name: "Gabon", dialCode: "+241" },
  { code: "CG", name: "Republic of the Congo", dialCode: "+242" },
  { code: "CD", name: "DR Congo", dialCode: "+243" },
  { code: "AO", name: "Angola", dialCode: "+244" },
  { code: "ZM", name: "Zambia", dialCode: "+260" },
  { code: "ZW", name: "Zimbabwe", dialCode: "+263" },
  { code: "MZ", name: "Mozambique", dialCode: "+258" },
  { code: "MW", name: "Malawi", dialCode: "+265" },
  { code: "NA", name: "Namibia", dialCode: "+264" },
  { code: "BW", name: "Botswana", dialCode: "+267" },
  { code: "ZA", name: "South Africa", dialCode: "+27" },
  { code: "SZ", name: "Eswatini", dialCode: "+268" },
  { code: "LS", name: "Lesotho", dialCode: "+266" },
  { code: "MG", name: "Madagascar", dialCode: "+261" },
  { code: "MU", name: "Mauritius", dialCode: "+230" },
  { code: "SC", name: "Seychelles", dialCode: "+248" },
  { code: "GM", name: "Gambia", dialCode: "+220" },
  { code: "GN", name: "Guinea", dialCode: "+224" },
  { code: "GW", name: "Guinea-Bissau", dialCode: "+245" },
  { code: "SL", name: "Sierra Leone", dialCode: "+232" },
  { code: "LR", name: "Liberia", dialCode: "+231" },
  { code: "TG", name: "Togo", dialCode: "+228" },
  { code: "BJ", name: "Benin", dialCode: "+229" },
  { code: "MR", name: "Mauritania", dialCode: "+222" },
  { code: "MX", name: "Mexico", dialCode: "+52" },
  { code: "GT", name: "Guatemala", dialCode: "+502" },
  { code: "BZ", name: "Belize", dialCode: "+501" },
  { code: "HN", name: "Honduras", dialCode: "+504" },
  { code: "SV", name: "El Salvador", dialCode: "+503" },
  { code: "NI", name: "Nicaragua", dialCode: "+505" },
  { code: "CR", name: "Costa Rica", dialCode: "+506" },
  { code: "PA", name: "Panama", dialCode: "+507" },
  { code: "CU", name: "Cuba", dialCode: "+53" },
  { code: "JM", name: "Jamaica", dialCode: "+1876" },
  { code: "HT", name: "Haiti", dialCode: "+509" },
  { code: "DO", name: "Dominican Republic", dialCode: "+1809" },
  { code: "BS", name: "Bahamas", dialCode: "+1242" },
  { code: "TT", name: "Trinidad and Tobago", dialCode: "+1868" },
  { code: "BB", name: "Barbados", dialCode: "+1246" },
  { code: "CO", name: "Colombia", dialCode: "+57" },
  { code: "VE", name: "Venezuela", dialCode: "+58" },
  { code: "GY", name: "Guyana", dialCode: "+592" },
  { code: "SR", name: "Suriname", dialCode: "+597" },
  { code: "EC", name: "Ecuador", dialCode: "+593" },
  { code: "PE", name: "Peru", dialCode: "+51" },
  { code: "BR", name: "Brazil", dialCode: "+55" },
  { code: "BO", name: "Bolivia", dialCode: "+591" },
  { code: "PY", name: "Paraguay", dialCode: "+595" },
  { code: "UY", name: "Uruguay", dialCode: "+598" },
  { code: "AR", name: "Argentina", dialCode: "+54" },
  { code: "CL", name: "Chile", dialCode: "+56" },
  { code: "FJ", name: "Fiji", dialCode: "+679" },
  { code: "PG", name: "Papua New Guinea", dialCode: "+675" },
  { code: "SB", name: "Solomon Islands", dialCode: "+677" },
  { code: "VU", name: "Vanuatu", dialCode: "+678" },
  { code: "WS", name: "Samoa", dialCode: "+685" },
  { code: "TO", name: "Tonga", dialCode: "+676" },
  { code: "KI", name: "Kiribati", dialCode: "+686" },
  { code: "FM", name: "Micronesia", dialCode: "+691" },
  { code: "PW", name: "Palau", dialCode: "+680" },
  { code: "MH", name: "Marshall Islands", dialCode: "+692" },
  { code: "NR", name: "Nauru", dialCode: "+674" },
  { code: "TV", name: "Tuvalu", dialCode: "+688" },
];

export const countriesByCode: Record<string, Country> = Object.fromEntries(
  countries.map((c) => [c.code, c])
);

export const countriesAlphabetical: Country[] = [...countries].sort((a, b) =>
  a.name.localeCompare(b.name)
);
