/**
 * Curated Lucide icon catalog for `IconPicker`. A deliberately-scoped
 * subset (not all ~1500 Lucide icons) keeps the picker fast to search and
 * the bundle small — extend `iconCatalog` with more entries as needed
 * instead of importing `lucide-react`'s full export map.
 */
import type { LucideIcon } from "lucide-react";
import {
  Activity, AlarmClock, AlertCircle, AlertTriangle, Archive, ArrowDown, ArrowLeft,
  ArrowRight, ArrowUp, AtSign, Award, Banknote, BarChart, Battery, Bell, Bike,
  Bookmark, Box, Briefcase, Bug, Building, Bus, Calendar, Camera, Car, Check,
  CheckCircle, ChevronDown, Clipboard, Clock, Cloud, CloudRain, Code, Coffee,
  Compass, Copy, CreditCard, Crown, Database, Download, Droplet, Edit, ExternalLink,
  Eye, EyeOff, FastForward, File, FileText, Film, Filter, Flag, Flame, Folder,
  Gift, GitBranch, Globe, Grid, HardDrive, Hash, Headphones, Heart, HelpCircle, Home,
  Image, Inbox, Info, Key, Laptop, Layers, Layout, LifeBuoy, Lightbulb, Link,
  List, Lock, LogOut, Mail, Map, MapPin, Maximize, Menu, MessageCircle,
  MessageSquare, Mic, Minus, Monitor, Moon, MoreHorizontal, Move, Music, Package,
  Paperclip, Pause, Percent, Phone, PieChart, Pin, Play, Plane, Plus,
  Power, Printer, Radio, RefreshCw, Repeat, Rocket, Rss, Save, Scissors, Search,
  Send, Server, Settings, Share2, Shield, ShieldCheck, ShoppingBag, ShoppingCart,
  Shuffle, Sliders, Smartphone, Smile, Snowflake, Speaker, Star, Sun, Sunrise,
  Table, Tablet, Tag, Target, Terminal, Thermometer, ThumbsDown, ThumbsUp,
  Ticket, ToggleLeft, Train, Trash2, TrendingUp, Truck, Tv, Umbrella,
  Unlock, Upload, User, Users, Video, Voicemail, Wallet, Watch, Wifi, Wind, Wrench,
  X, Zap, ZoomIn,
} from "lucide-react";

export interface IconCatalogEntry {
  name: string;
  icon: LucideIcon;
  category: IconCategory;
  keywords: string[];
}

export const iconCategories = [
  "General",
  "Arrows & Actions",
  "Communication",
  "Files & Data",
  "Media",
  "Commerce",
  "Devices & Tech",
  "Weather",
  "People & Status",
  "Travel & Places",
] as const;

export type IconCategory = (typeof iconCategories)[number];

export const iconCatalog: IconCatalogEntry[] = [
  { name: "Activity", icon: Activity, category: "General", keywords: ["pulse", "health"] },
  { name: "AlarmClock", icon: AlarmClock, category: "General", keywords: ["alarm", "time"] },
  { name: "AlertCircle", icon: AlertCircle, category: "General", keywords: ["warning", "error"] },
  { name: "AlertTriangle", icon: AlertTriangle, category: "General", keywords: ["warning", "caution"] },
  { name: "Archive", icon: Archive, category: "Files & Data", keywords: ["box", "storage"] },
  { name: "ArrowDown", icon: ArrowDown, category: "Arrows & Actions", keywords: ["down"] },
  { name: "ArrowLeft", icon: ArrowLeft, category: "Arrows & Actions", keywords: ["back", "left"] },
  { name: "ArrowRight", icon: ArrowRight, category: "Arrows & Actions", keywords: ["forward", "right"] },
  { name: "ArrowUp", icon: ArrowUp, category: "Arrows & Actions", keywords: ["up"] },
  { name: "AtSign", icon: AtSign, category: "Communication", keywords: ["email", "mention"] },
  { name: "Award", icon: Award, category: "People & Status", keywords: ["badge", "achievement"] },
  { name: "Banknote", icon: Banknote, category: "Commerce", keywords: ["money", "cash"] },
  { name: "BarChart", icon: BarChart, category: "General", keywords: ["chart", "analytics"] },
  { name: "Battery", icon: Battery, category: "Devices & Tech", keywords: ["power", "charge"] },
  { name: "Bell", icon: Bell, category: "Communication", keywords: ["notification", "alert"] },
  { name: "Bike", icon: Bike, category: "Travel & Places", keywords: ["cycle", "transport"] },
  { name: "Bookmark", icon: Bookmark, category: "General", keywords: ["save"] },
  { name: "Box", icon: Box, category: "Files & Data", keywords: ["package", "cube"] },
  { name: "Briefcase", icon: Briefcase, category: "Commerce", keywords: ["work", "job"] },
  { name: "Bug", icon: Bug, category: "Devices & Tech", keywords: ["issue", "error"] },
  { name: "Building", icon: Building, category: "Travel & Places", keywords: ["office", "company"] },
  { name: "Bus", icon: Bus, category: "Travel & Places", keywords: ["transport"] },
  { name: "Calendar", icon: Calendar, category: "General", keywords: ["date", "schedule"] },
  { name: "Camera", icon: Camera, category: "Media", keywords: ["photo"] },
  { name: "Car", icon: Car, category: "Travel & Places", keywords: ["vehicle", "transport"] },
  { name: "Check", icon: Check, category: "General", keywords: ["done", "success"] },
  { name: "CheckCircle", icon: CheckCircle, category: "People & Status", keywords: ["success", "done"] },
  { name: "ChevronDown", icon: ChevronDown, category: "Arrows & Actions", keywords: ["expand"] },
  { name: "Clipboard", icon: Clipboard, category: "Files & Data", keywords: ["copy", "paste"] },
  { name: "Clock", icon: Clock, category: "General", keywords: ["time"] },
  { name: "Cloud", icon: Cloud, category: "Weather", keywords: ["overcast"] },
  { name: "CloudRain", icon: CloudRain, category: "Weather", keywords: ["rain"] },
  { name: "Code", icon: Code, category: "Devices & Tech", keywords: ["development"] },
  { name: "Coffee", icon: Coffee, category: "General", keywords: ["break", "drink"] },
  { name: "Compass", icon: Compass, category: "Travel & Places", keywords: ["navigation"] },
  { name: "Copy", icon: Copy, category: "Files & Data", keywords: ["duplicate"] },
  { name: "CreditCard", icon: CreditCard, category: "Commerce", keywords: ["payment", "billing"] },
  { name: "Crown", icon: Crown, category: "People & Status", keywords: ["premium", "admin"] },
  { name: "Database", icon: Database, category: "Devices & Tech", keywords: ["storage", "data"] },
  { name: "Download", icon: Download, category: "Arrows & Actions", keywords: ["save"] },
  { name: "Droplet", icon: Droplet, category: "Weather", keywords: ["water", "humidity"] },
  { name: "Edit", icon: Edit, category: "General", keywords: ["pencil", "modify"] },
  { name: "ExternalLink", icon: ExternalLink, category: "Arrows & Actions", keywords: ["open", "link"] },
  { name: "Eye", icon: Eye, category: "General", keywords: ["view", "visible"] },
  { name: "EyeOff", icon: EyeOff, category: "General", keywords: ["hide", "hidden"] },
  { name: "FastForward", icon: FastForward, category: "Media", keywords: ["skip"] },
  { name: "File", icon: File, category: "Files & Data", keywords: ["document"] },
  { name: "FileText", icon: FileText, category: "Files & Data", keywords: ["document", "text"] },
  { name: "Film", icon: Film, category: "Media", keywords: ["video", "movie"] },
  { name: "Filter", icon: Filter, category: "General", keywords: ["sort"] },
  { name: "Flag", icon: Flag, category: "General", keywords: ["report", "mark"] },
  { name: "Flame", icon: Flame, category: "Weather", keywords: ["fire", "hot"] },
  { name: "Folder", icon: Folder, category: "Files & Data", keywords: ["directory"] },
  { name: "Gift", icon: Gift, category: "Commerce", keywords: ["present", "reward"] },
  { name: "GitBranch", icon: GitBranch, category: "Devices & Tech", keywords: ["git", "code", "version control"] },
  { name: "Globe", icon: Globe, category: "Travel & Places", keywords: ["world", "web"] },
  { name: "Grid", icon: Grid, category: "General", keywords: ["layout"] },
  { name: "HardDrive", icon: HardDrive, category: "Devices & Tech", keywords: ["storage", "disk"] },
  { name: "Hash", icon: Hash, category: "Communication", keywords: ["tag", "channel"] },
  { name: "Headphones", icon: Headphones, category: "Media", keywords: ["audio"] },
  { name: "Heart", icon: Heart, category: "General", keywords: ["like", "favorite"] },
  { name: "HelpCircle", icon: HelpCircle, category: "General", keywords: ["question", "support"] },
  { name: "Home", icon: Home, category: "Travel & Places", keywords: ["house"] },
  { name: "Image", icon: Image, category: "Media", keywords: ["picture", "photo"] },
  { name: "Inbox", icon: Inbox, category: "Communication", keywords: ["mail"] },
  { name: "Info", icon: Info, category: "General", keywords: ["information"] },
  { name: "Key", icon: Key, category: "General", keywords: ["password", "security"] },
  { name: "Laptop", icon: Laptop, category: "Devices & Tech", keywords: ["computer"] },
  { name: "Layers", icon: Layers, category: "General", keywords: ["stack"] },
  { name: "Layout", icon: Layout, category: "General", keywords: ["template"] },
  { name: "LifeBuoy", icon: LifeBuoy, category: "General", keywords: ["support", "help"] },
  { name: "Lightbulb", icon: Lightbulb, category: "General", keywords: ["idea"] },
  { name: "Link", icon: Link, category: "General", keywords: ["url", "chain"] },
  { name: "List", icon: List, category: "General", keywords: ["items"] },
  { name: "Lock", icon: Lock, category: "General", keywords: ["security", "private"] },
  { name: "LogOut", icon: LogOut, category: "People & Status", keywords: ["sign out"] },
  { name: "Mail", icon: Mail, category: "Communication", keywords: ["email"] },
  { name: "Map", icon: Map, category: "Travel & Places", keywords: ["location"] },
  { name: "MapPin", icon: MapPin, category: "Travel & Places", keywords: ["location", "pin"] },
  { name: "Maximize", icon: Maximize, category: "General", keywords: ["expand", "fullscreen"] },
  { name: "Menu", icon: Menu, category: "General", keywords: ["hamburger", "navigation"] },
  { name: "MessageCircle", icon: MessageCircle, category: "Communication", keywords: ["chat"] },
  { name: "MessageSquare", icon: MessageSquare, category: "Communication", keywords: ["chat", "comment"] },
  { name: "Mic", icon: Mic, category: "Media", keywords: ["microphone", "audio"] },
  { name: "Minus", icon: Minus, category: "General", keywords: ["remove", "subtract"] },
  { name: "Monitor", icon: Monitor, category: "Devices & Tech", keywords: ["screen", "display"] },
  { name: "Moon", icon: Moon, category: "Weather", keywords: ["night", "dark mode"] },
  { name: "MoreHorizontal", icon: MoreHorizontal, category: "General", keywords: ["options", "menu"] },
  { name: "Move", icon: Move, category: "Arrows & Actions", keywords: ["drag"] },
  { name: "Music", icon: Music, category: "Media", keywords: ["audio", "song"] },
  { name: "Package", icon: Package, category: "Commerce", keywords: ["box", "shipping"] },
  { name: "Paperclip", icon: Paperclip, category: "Files & Data", keywords: ["attachment"] },
  { name: "Pause", icon: Pause, category: "Media", keywords: ["stop"] },
  { name: "Percent", icon: Percent, category: "Commerce", keywords: ["discount"] },
  { name: "Phone", icon: Phone, category: "Communication", keywords: ["call"] },
  { name: "PieChart", icon: PieChart, category: "General", keywords: ["chart", "analytics"] },
  { name: "Pin", icon: Pin, category: "General", keywords: ["pinned"] },
  { name: "Play", icon: Play, category: "Media", keywords: ["start"] },
  { name: "Plane", icon: Plane, category: "Travel & Places", keywords: ["flight", "travel"] },
  { name: "Plus", icon: Plus, category: "General", keywords: ["add", "new"] },
  { name: "Power", icon: Power, category: "Devices & Tech", keywords: ["on off"] },
  { name: "Printer", icon: Printer, category: "Devices & Tech", keywords: ["print"] },
  { name: "Radio", icon: Radio, category: "Media", keywords: ["broadcast"] },
  { name: "RefreshCw", icon: RefreshCw, category: "Arrows & Actions", keywords: ["reload", "sync"] },
  { name: "Repeat", icon: Repeat, category: "Media", keywords: ["loop"] },
  { name: "Rocket", icon: Rocket, category: "General", keywords: ["launch", "deploy"] },
  { name: "Rss", icon: Rss, category: "Communication", keywords: ["feed"] },
  { name: "Save", icon: Save, category: "General", keywords: ["disk", "store"] },
  { name: "Scissors", icon: Scissors, category: "General", keywords: ["cut"] },
  { name: "Search", icon: Search, category: "General", keywords: ["find"] },
  { name: "Send", icon: Send, category: "Communication", keywords: ["submit"] },
  { name: "Server", icon: Server, category: "Devices & Tech", keywords: ["backend"] },
  { name: "Settings", icon: Settings, category: "General", keywords: ["gear", "preferences"] },
  { name: "Share2", icon: Share2, category: "Communication", keywords: ["share"] },
  { name: "Shield", icon: Shield, category: "General", keywords: ["security"] },
  { name: "ShieldCheck", icon: ShieldCheck, category: "General", keywords: ["verified", "security"] },
  { name: "ShoppingBag", icon: ShoppingBag, category: "Commerce", keywords: ["store"] },
  { name: "ShoppingCart", icon: ShoppingCart, category: "Commerce", keywords: ["cart"] },
  { name: "Shuffle", icon: Shuffle, category: "Media", keywords: ["random"] },
  { name: "Sliders", icon: Sliders, category: "General", keywords: ["settings", "controls"] },
  { name: "Smartphone", icon: Smartphone, category: "Devices & Tech", keywords: ["mobile", "phone"] },
  { name: "Smile", icon: Smile, category: "People & Status", keywords: ["emoji", "happy"] },
  { name: "Snowflake", icon: Snowflake, category: "Weather", keywords: ["cold", "winter"] },
  { name: "Speaker", icon: Speaker, category: "Media", keywords: ["audio", "sound"] },
  { name: "Star", icon: Star, category: "General", keywords: ["favorite", "rating"] },
  { name: "Sun", icon: Sun, category: "Weather", keywords: ["light mode", "day"] },
  { name: "Sunrise", icon: Sunrise, category: "Weather", keywords: ["morning"] },
  { name: "Table", icon: Table, category: "Files & Data", keywords: ["grid", "data"] },
  { name: "Tablet", icon: Tablet, category: "Devices & Tech", keywords: ["ipad"] },
  { name: "Tag", icon: Tag, category: "General", keywords: ["label"] },
  { name: "Target", icon: Target, category: "General", keywords: ["goal"] },
  { name: "Terminal", icon: Terminal, category: "Devices & Tech", keywords: ["console", "code"] },
  { name: "Thermometer", icon: Thermometer, category: "Weather", keywords: ["temperature"] },
  { name: "ThumbsDown", icon: ThumbsDown, category: "People & Status", keywords: ["dislike"] },
  { name: "ThumbsUp", icon: ThumbsUp, category: "People & Status", keywords: ["like"] },
  { name: "Ticket", icon: Ticket, category: "Commerce", keywords: ["pass", "event"] },
  { name: "ToggleLeft", icon: ToggleLeft, category: "General", keywords: ["switch"] },
  { name: "Wrench", icon: Wrench, category: "Devices & Tech", keywords: ["tool", "settings", "repair"] },
  { name: "Train", icon: Train, category: "Travel & Places", keywords: ["transport"] },
  { name: "Trash2", icon: Trash2, category: "General", keywords: ["delete", "remove"] },
  { name: "TrendingUp", icon: TrendingUp, category: "General", keywords: ["growth", "analytics"] },
  { name: "Truck", icon: Truck, category: "Commerce", keywords: ["shipping", "delivery"] },
  { name: "Tv", icon: Tv, category: "Media", keywords: ["television"] },
  { name: "Umbrella", icon: Umbrella, category: "Weather", keywords: ["rain"] },
  { name: "Unlock", icon: Unlock, category: "General", keywords: ["open", "security"] },
  { name: "Upload", icon: Upload, category: "Arrows & Actions", keywords: ["send"] },
  { name: "User", icon: User, category: "People & Status", keywords: ["person", "profile"] },
  { name: "Users", icon: Users, category: "People & Status", keywords: ["team", "group"] },
  { name: "Video", icon: Video, category: "Media", keywords: ["camera"] },
  { name: "Voicemail", icon: Voicemail, category: "Communication", keywords: ["message"] },
  { name: "Wallet", icon: Wallet, category: "Commerce", keywords: ["money", "payment"] },
  { name: "Watch", icon: Watch, category: "Devices & Tech", keywords: ["time", "wearable"] },
  { name: "Wifi", icon: Wifi, category: "Devices & Tech", keywords: ["network", "internet"] },
  { name: "Wind", icon: Wind, category: "Weather", keywords: ["breeze"] },
  { name: "X", icon: X, category: "General", keywords: ["close", "cancel"] },
  { name: "Zap", icon: Zap, category: "General", keywords: ["lightning", "fast"] },
  { name: "ZoomIn", icon: ZoomIn, category: "General", keywords: ["magnify"] },
];

export const iconCatalogByName: Record<string, IconCatalogEntry> = Object.fromEntries(
  iconCatalog.map((entry) => [entry.name, entry])
);
