/**
 * Typed route map — single source of truth for navigation hrefs.
 */

export const routes = {
  home: "/",
  designSystem: "/design-system",
  shellPreview: "/shell-preview",

  auth: {
    login: "/login",
    register: "/register",
    forgotPassword: "/forgot-password",
    resetPassword: "/reset-password",
    verifyEmail: "/verify-email",
    callback: "/auth/callback",
    /** @deprecated Use `login` */
    signIn: "/login",
    /** @deprecated Use `register` */
    signUp: "/register",
  },

  app: {
    home: "/dashboard",
    dashboard: "/dashboard",
    profile: "/profile",
    account: {
      settings: "/account/settings",
      notifications: "/account/notifications",
      security: "/account/security",
    },
    organizations: "/organizations",
    organizationNew: "/organizations/new",
    organization: (id: string) => `/organizations/${id}` as const,
    organizationTeams: (id: string) => `/organizations/${id}/teams` as const,
    projects: "/projects",
    projectNew: "/projects/new",
    project: (id: string) => `/projects/${id}` as const,
    projectEdit: (id: string) => `/projects/${id}/edit` as const,
    projectSettings: (id: string) => `/projects/${id}/settings` as const,
    projectActivity: (id: string) => `/projects/${id}/activity` as const,
    projectMembers: (id: string) => `/projects/${id}/members` as const,
    projectAnalytics: (id: string) => `/projects/${id}/analytics` as const,
    projectRepository: (id: string) => `/projects/${id}/repository` as const,
    projectEnvironments: (id: string) => `/projects/${id}/environments` as const,
    tasks: "/tasks",
    taskNew: "/tasks/new",
    task: (id: string) => `/tasks/${id}` as const,
    taskEdit: (id: string) => `/tasks/${id}/edit` as const,
    projectTasks: (projectId: string) => `/projects/${projectId}/tasks` as const,
    projectBoard: (projectId: string) => `/projects/${projectId}/board` as const,
    sprints: "/sprints",
    sprintNew: "/sprints/new",
    sprint: (id: string) => `/sprints/${id}` as const,
    sprintEdit: (id: string) => `/sprints/${id}/edit` as const,
    projectSprints: (projectId: string) => `/projects/${projectId}/sprints` as const,
    projectBacklog: (projectId: string) => `/projects/${projectId}/backlog` as const,
    projectReleases: (projectId: string) => `/projects/${projectId}/releases` as const,
    projectReports: (projectId: string) => `/projects/${projectId}/reports` as const,
    deployments: "/deployments",
    repositories: "/repositories",
    repositoryNew: "/repositories/new",
    repository: (id: string) => `/repositories/${id}` as const,
    repositorySettings: (id: string) => `/repositories/${id}/settings` as const,
    repositoryBranches: (id: string) => `/repositories/${id}/branches` as const,
    repositoryCommits: (id: string) => `/repositories/${id}/commits` as const,
    repositoryReleases: (id: string) => `/repositories/${id}/releases` as const,
    repositoryPullRequests: (id: string) => `/repositories/${id}/pull-requests` as const,
    repositoryFiles: (id: string) => `/repositories/${id}/files` as const,
    repositoryWebhooks: (id: string) => `/repositories/${id}/webhooks` as const,
    documents: "/documents",
    documentNew: "/documents/new",
    document: (id: string) => `/documents/${id}` as const,
    documentEdit: (id: string) => `/documents/${id}/edit` as const,
    documentTemplates: "/documents/templates",
    documentFavorites: "/documents/favorites",
    documentRecent: "/documents/recent",
    documentShared: "/documents/shared",
    analytics: "/analytics",
    analyticsReports: "/analytics/reports",
    analyticsExecutive: "/analytics/executive",
    monitoring: "/monitoring",
    monitoringServices: "/monitoring/services",
    monitoringAlerts: "/monitoring/alerts",
    monitoringIncidents: "/monitoring/incidents",
    monitoringErrors: "/monitoring/errors",
    monitoringAudit: "/monitoring/audit",
    settings: {
      root: "/account/settings",
      profile: "/profile",
      organization: "/settings/organization",
      members: "/settings/members",
      roles: "/settings/roles",
      security: "/account/security",
    },
  },
} as const;

export type AppRoutes = typeof routes;
